config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  resources :static, only: [] do 
    get :home
  end

  root 'static#home'
  
  resources :accounts, only: [:create] do
    collection do
      post :revoke
      post :refresh
      get :sign_in
      get :sign_up
      delete :sign_out
    end
  end

  resources :users, only: [:create, :update, :show] do
    collection do
      get :check_email
      get :edit_password
      post :reset_password
      get :forget_password
      get :dashboard
      get :me
      post '/me/change_password', to: 'users#change_password'
      get '/me/widgets', to: 'users#widgets'
    end
  end

  resources :widgets
end

app/models/application_record.rb
# class ApplicationRecord < ActiveRecord::Base
#   self.abstract_class = true
# end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def create
    account = Authentications.create(query: session_params)
    @response = account.parsed_response
    if account.code == 200
      save_user_session
      redirect_to dashboard_users_path
    else
      redirect_to sign_in_accounts_path, flash: {error: @response["messasge"]}
    end
  end

  def sign_out
    if current_user.present?
      clear_sessions
      redirect_to sign_in_accounts_path
    else
      redirect_back dashboard_users_path, flash: {notice: 'Something went wrong'}
    end
  end

  def revoke
  end

  def refresh
  end

  private

  def session_params
    params.require(:account).permit(:username, :password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :signed_in?

  def signed_in?
    return true if cookies.signed[:user].present?
  end

  def current_user
    @current_user = cookies.signed[:user]
  end

  def save_user_session
    session[:user_token] = @response["data"]["token"]["access_token"]
    session[:refresh_token] = @response["data"]["token"]["refresh_token"]
    save_user_details if @response["data"].try(:[], "user").present?
  end

  def save_user_details
    cookies.signed[:user] = {value: @response["data"].try(:[], "user"), expires: 8.hours.from_now}
  end

  def clear_sessions
    session[:user_token] = session[:refresh_token] = cookies.signed[:user] = nil
  end

  def set_auth_header
    @header ||= {}
    @header.merge!({"Authorization" => "Bearer #{session[:user_token]}"})
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_auth_header, except: [:create, :reset_password, :check_email]
  before_action :get_user, only: [:dashboard, :me]

  def create
    @users = Users.create(query: auth_params)
    @response = @users.parsed_response
    if @users.code == 200
      save_user_session
      redirect_to sign_in_accounts_path
    else
      redirect_to sign_up_accounts_path, flash: {alert: @response["message"]}
    end
  end

  def dashboard
  end

  def show
    
  end

  def widgets
    query = params[:term].present? ? {term: params[:term]} : {}
    @response = Users.widgets(query: query, headers: @header)
    if @response.code == 200
      @widgets = @response.parsed_response["data"]["widgets"]
    else
      @widgets = []
    end
  end

  def me
  end

  def update
    params[:user][:date_of_birth] = Time.parse(params[:user][:date_of_birth]).to_i if params[:user][:date_of_birth].present?
    @response = Users.update_me query: {user: user_params}, headers: @header
    @user = @response.parsed_response
    if @response.code == 200
      @response = @response.parsed_response
      save_user_details
      redirect_to me_users_path, flash: {notice: 'Successfully updated'}
    else
      redirect_to me_users_path, flash: {alert: 'Something went wrong'}
    end
  end

  def change_password
    @response = Users.change_password query: {user: password_params}, headers: @header
    if @response.code == 200 
      @response = @response.parsed_response
      clear_sessions
      redirect_to sign_in_accounts_path, flash: {notice: 'Successfully updated password'}
    else
      redirect_to edit_password_users_path, flash: {alert: 'Password mismatch'}
    end
  end

  def check_email
    response = Users.check_email(query: {email: params[:email]})
    render json: {}, status: response.code
  end

  def reset_password
    @response = Users.reset_password(query: {user: reset_params})
    if @response.code == 200
      redirect_to sign_in_accounts_path, flash: {notice: @response.parsed_response["message"]}
    else
      redirect_to forget_password_users_path, flash: {alert: @response.parsed_response["message"]}
    end
  end

  private

  def get_user
    if current_user.present?
      @user = current_user
    else
      @header ||= {}
      @user = Users.me(headers: @header)
      if @user.code == 200
        @response = @user.parsed_response
        @user = @response["data"]["user"]
        save_user_details
      else
        redirect_to sign_in_accounts_path
      end 
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :password, :image_url, :date_of_birth)
  end

  def auth_params
    params.require(:account).permit(user: [:first_name, :last_name, :password, :email])
  end

  def reset_params
    params.require(:user).permit(:email)
  end

  def password_params
    params.require(:user).permit(:new_password, :current_password)
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_auth_header
  before_action :set_kind, only: [:create, :update]

  def create
    if params[:id].present?
      update_widgets
    else
      add_widgets
    end
  end

  def new
  end

  def show
    @response = Widgets.find(query: {widget: widget_params}, headers: @header) 
  end

  def index
    @response = Widgets.find(:all, query: {term: params[:term]}, headers: @header, parsed: false)
    if @response.code == 200
      @widgets = @response.parsed_response["data"]["widgets"]
    else
      @widgets = []
    end
  end

  def update
    @response = Widgets.update(query: {widget: widget_params}, headers: @header)  
  end

  def destroy
    @response = Widgets.destroy(query: {id: params[:id]}, headers: @header)
    if @response.code == 200
      redirect_to widgets_path, flash: {notice: 'Deleted Successfully'}
    else
      redirect_to widgets_path, flash: {alert: 'Something Went wrong'}
    end
  end

  private 

  def add_widgets
    @response = Widgets.create(query: {widget: widget_params}, headers: @header)
    @widget = @response.parsed_response
    if @response.code == 200
      redirect_to widgets_path, flash: {notice: 'Created Widget Successfully'}
    else
      redirect_to new_widget_path, flash: {alert: @widget["message"]}
    end
  end

  def update_widgets
    @response = Widgets.update(query: {id: params[:id], widget: widget_params}, headers: @header)  
    @widget = @response.parsed_response
    if @response.code == 200
      redirect_to widgets_path, flash: {notice: 'Updated Widget Successfully'}
    else
      redirect_to widgets_path, flash: {alert: @widget["message"]}
    end
  end

  def set_kind
    params[:widget][:kind] = params[:widget][:kind].present? ? 'visible' : 'hidden' 
  end

  def widget_params
    params.require(:widget).permit(:id, :name, :description, :kind)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_flash
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = <<-JS
              <script> 
                toastr['#{type}']("#{message}");
              </script>
             JS
      flash_messages << text.html_safe if message
    end
    flash.discard
    flash_messages.join("\n").html_safe
  end
end

app/views/accounts/sign_in.html.erb
 <%= form_tag accounts_path, class: 'form-signin text-center' do  %>
  <%= image_tag 'logo.png', class: 'mb-4 text-center', width: '72', height: '72' %>
  <div class="form-group">
    <%= text_field_tag 'account[username]', nil, class: 'form-control slide-1', placeholder: 'Email' %>
  </div>
  <div class="form-group">
    <%= password_field_tag 'account[password]', nil, class: 'form-control slide-2 ', placeholder: 'Password' %>
  </div>
  <div class="clearfix">
  </div>
  <button class="btn btn-md btn-red btn-block slide-1" id="validate-email">Next</button>
  <button class="btn btn-md btn-red btn-block slide-2" type="submit">Sign in</button>

  <%= link_to 'Forget Password?', forget_password_users_path %>
<% end %>


<%= content_for :javascripts do %>
  <script type="text/javascript">
    $(document).ready(function(){
      $('#validate-email').on('click', function(e) {
        e.preventDefault();
        $.ajax({
          url: "<%= check_email_users_path(format: :json) %>",
          data: {email: $('#account_username').val()},
          success: function(data){
            $('.slide-1').hide();
            $('.slide-2').show();
          },
          error: function(data) {
            alert('email does not exist');
          }
        })
      });
    });
  </script>
<% end %>

app/views/accounts/sign_up.html.erb
 <%= form_tag users_path, class: 'form-signin text-center' do  %>
  <%= image_tag 'logo.png', class: 'mb-4 text-center', width: '72', height: '72' %>
  <%= text_field_tag 'account[user][first_name]', nil, class: 'form-control', placeholder: 'first name' %>
  <%= text_field_tag 'account[user][last_name]', nil, class: 'form-control', placeholder: 'last name' %>
  <%= text_field_tag 'account[user][email]', nil, class: 'form-control', placeholder: 'email' %>
  <%= password_field_tag 'account[user][password]', nil, class: 'form-control', placeholder: 'password' %>
  <%= password_field_tag 'account[user][password_confirmation]', nil, class: 'form-control', placeholder: 'password confirmation' %>
  <%= text_field_tag 'account[user][image_url]', nil, class: 'form-control', placeholder: 'Image Url' %>
  <div class="clearfix"></div>
  <button class="btn btn-lg btn-red btn-block" type="submit">Sign in</button>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Showoff</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  </head>

  <body>
    <div class="cover-container container d-flex p-3 flex-column">
    <header class="masthead">
      <div class="inner">
        <h3 class="masthead-brand"><%= image_tag 'logo.png', width: 40, height: 40 %></h3>
        <nav class="nav nav-masthead justify-content-center">
          <div class="nav-item">
            <%= link_to root_path, class: 'nav-link active' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </div>
          <% if current_user.present? %>
            <div class="nav-item">
              <%= link_to widgets_path, class: 'nav-link' do %>
                <i class="fas fa-cubes"></i> Widgets
              <% end %>
            </div>
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown06" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user"></i> Accounts</a>
              <div class="dropdown-menu" aria-labelledby="dropdown06" bis_skin_checked="1">
                <%= link_to 'View Profile', me_users_path, class: 'nav-link' %>
                <%= link_to 'Logout', sign_out_accounts_path, method: :delete, class: 'nav-link' %>
              </div>
            </div>
          <% else %>
            <div class="nav-item">
              <%= link_to 'Sign In', sign_in_accounts_path, class: 'nav-link' %>
            </div>
            <div class="nav-item">
              <%= link_to 'Sign Up', sign_up_accounts_path, class: 'nav-link' %>
            </div>
          <% end %>
        </nav>
      </div>
    </header>
    <main role="main" class="inner cover">
      <%= yield %>
    </main>

    <footer class="mastfoot mt-auto">
      <div class="inner">
      </div>
    </footer>
  </div>
  <div class="loader">
    <div class="spinner-grow text-primary" role="status">
      <span class="sr-only">Loading...</span>
    </div>
    <div class="spinner-grow text-secondary" role="status">
      <span class="sr-only">Loading...</span>
    </div>
    <div class="spinner-grow text-success" role="status">
      <span class="sr-only">Loading...</span>
    </div>
    <div class="spinner-grow text-danger" role="status">
      <span class="sr-only">Loading...</span>
    </div>
    <div class="spinner-grow text-warning" role="status">
      <span class="sr-only">Loading...</span>
    </div>
    <div class="spinner-grow text-info" role="status">
      <span class="sr-only">Loading...</span>
    </div>
    <div class="spinner-grow text-light" role="status">
      <span class="sr-only">Loading...</span>
    </div>
    <div class="spinner-grow text-dark" role="status">
      <span class="sr-only">Loading...</span>
    </div>
  </div>
  <%= custom_flash %>
  <%= yield :javascripts %>
  </body>
</html>

app/views/users/_profile.html.erb
<% user = cookies.signed[:user] %>
<div class="container">
  <div class="row content profile" style="background: #fff;">
    <div class="col-md-3">
      <div class="profile-sidebar">
				<!-- SIDEBAR USERPIC -->
				<div class="profile-userpic">
          <%= image_tag user["images"]["small_url"], class: "img-responsive" %>
				</div>
				<!-- END SIDEBAR USERPIC -->
				<!-- SIDEBAR USER TITLE -->
				<div class="profile-usertitle">
					<div class="profile-usertitle-name">
						<%= user["name"] %>
					</div>
					<div class="profile-usertitle-job">
						<%= user["email"] %>
					</div>
				</div>
				<!-- END SIDEBAR USER TITLE -->
			</div>
      <ul class="list-group profile-usermenu">
        <li class="list-group-item">
          <%= link_to 'Widgets', me_widgets_users_path %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Change Password', edit_password_users_path %>
        </li>
      </ul>
    </div>
    <div class="col-md-9">
       <%= form_tag user_path(user["id"]), { class: 'form-signin', method: :put} do  %>
        <div class="form-group">
          <label>Name</label>
          <%= text_field_tag 'user[first_name]', user["first_name"], class: 'form-control', placeholder: 'First Name' %>
        </div>
        <div class="form-group">
          <label>Last Name</label>
          <%= text_field_tag 'user[last_name]', user["last_name"], class: 'form-control', placeholder: 'Last Name' %>
        </div>
        <div class="form-group">
          <label>Date Of Birth</label>
          <%= text_field_tag 'user[date_of_birth]', (user["date_of_birth"].nil? ? nil : Time.at(user["date_of_birth"]).strftime('%d-%m-%Y')), class: 'form-control', placeholder: 'dd-mm-yyyy' %>
        </div>
        <div class="form-group">
          <label>Image Url</label>
          <%= text_field_tag 'user[image_url]', nil, class: 'form-control', placeholder: 'Image Url' %>
        </div>
        <div class="clearfix">
        </div>
        <button class="btn btn-md btn-red btn-block" type="submit">Save</button>
      <% end %>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
<% user = cookies.signed[:user] %>
<% if user.present? %>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag user["images"]["small_url"], width: 70, height: 70 %>
      </div>
      <div class="col-md-8">
        <h3><%= user["name"] %></h3>
        <p><%= user["email"] %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit_password.html.erb
 <%= form_tag me_change_password_users_path, class: 'form-signin' do  %>
  <div class="form-group">
    <label>Current Password</label>
    <%= password_field_tag 'user[current_password]', nil, class: 'form-control', placeholder: 'Current Password' %>
  </div>
  <div class="form-group">
    <label>New Password</label>
    <%= password_field_tag 'user[new_password]', nil, class: 'form-control', placeholder: 'New Password' %>
  </div>
  <div class="clearfix">
  </div>
  <button class="btn btn-md btn-red btn-block" type="submit">Change Password</button>
<% end %>

app/views/users/forget_password.html.erb
 <%= form_tag reset_password_users_path, class: 'form-signin text-center' do  %>
  <%= image_tag 'logo.png', class: 'mb-4 text-center', width: '72', height: '72' %>
  <div class="form-group">
    <%= text_field_tag 'user[email]', nil, class: 'form-control', placeholder: 'Email' %>
  </div>
  <div class="clearfix">
  </div>
  <button class="btn btn-md btn-red btn-block" type="submit">Reset Password</button>
<% end %>

app/views/users/me.html.erb
<%= render 'profile' %>

app/views/users/show.html.erb
<%= render 'profile' %>

app/views/users/widgets.html.erb
<%= form_tag me_widgets_users_path, {method: :get} do %>
  <div class="form-group">
    <%= text_field_tag 'term', nil %>
    <button type="submit" class="btn btn-sm btn-red mb-2"><i class="fas fa-search"></i></button>
    <%= link_to new_widget_path, class: 'btn btn-sm btn-red mb-2' do %>
      <i class="fas fa-plus"></i>
    <% end %>
  </div>
<% end %>
<%= render '/widgets/widgets' %>

app/views/widgets/_form.html.erb
 <%= form_tag widgets_path do  %>
  <%= hidden_field_tag 'id', nil, id: 'widget_id' %>
  <div class="form-group">
    <label>Name</label>
    <%= text_field_tag 'widget[name]', nil, class: 'form-control', placeholder: 'Name' %>
  </div>
  <div class="form-group">
    <label>Description</label>
    <%= text_area_tag 'widget[description]', nil, class: 'form-control', placeholder: 'Description' %>
  </div>
  <div class="form-group">
    <label>Visibility</label>
    <div class="clearfix"></div>
    <label class="switch">
      <%= check_box_tag 'widget[kind]', nil, false, class: 'form-control' %>  
      <div></div>
    </label>
  </div>
  <button class="btn btn-md btn-red btn-block" type="submit">Save</button>
<% end %>

app/views/widgets/_widgets.html.erb
<% @widgets.each do |widget| %>
  <div class="card widget-type-<%= widget["kind"] %>">
    <div class="card-body">
      <h4><%= widget["name"] %></h4>
      <p><%= widget["description"] %></p>
      <div class="widget-info">
        <span>by <%= widget["user"]["name"] %></span>
        
        <div class="float-right">
          <a href="#" data-toggle="modal" data-target="#widget-form" data-params="<%= widget.to_json %>">
            <i class="fas fa-edit"></i>
          </a>
          <%= link_to widget_path(widget["id"]), method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="modal" id="widget-form">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Edit Widget</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">

      </div>
    </div>
  </div>
</div>

<%= content_for :javascripts do %>
  <script type="text/javascript">
    $(document).ready(function(){
      $widget_form = "<%=j render '/widgets/form' %>";
      $("#widget-form").on('show.bs.modal', function(e){
        var $invoker = $(e.relatedTarget);
        var $widget = JSON.parse($($invoker).attr('data-params'))
        $('#widget-form .modal-body').html($widget_form);
        $('#widget_name').val($widget["name"]);
        $('#widget_description').val($widget["description"]);
        if ($widget["kind"] == "visible") {
          $('#widget_kind').attr('checked', 'checked');
          $('#widget_kind').val($widget["kind"]);
        }
        $('#widget_id').val($widget["id"]);
      });
    });
  </script>
<% end %>

app/views/widgets/index.html.erb
<%= form_tag widgets_path, {method: :get} do %>
  <div class="form-group">
    <%= text_field_tag 'term', nil %>
    <button type="submit" class="btn btn-sm btn-red mb-2"><i class="fas fa-search"></i></button>
    <%= link_to new_widget_path, class: 'btn btn-sm btn-red mb-2' do %>
      <i class="fas fa-plus"></i>
    <% end %>
  </div>
<% end %>
<%= render 'widgets' %>

app/views/widgets/new.html.erb
<%= render 'form' %>